version: '3'
services:

  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    hostname: mongodb
    # environment: 
      # - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      # - MONGO_INITDB_DATABASE=graylog
    networks:
      - graylog-net
  # БД расшарена для сохранения данных
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: elasticsearch:7.17.1
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - xpack.security.enabled=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - graylog-net

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.2
    container_name: graylog
    hostname: graylog
    # каталоги журнала и конфигурации в локальной NFS расшарены для сохранения данных
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
      # MONGODB_URI=mongodb://user:password@localhost:27017/graylog
    environment:
      # CHANGE ME (должно быть не менее 16 символов)!
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      # Пароль: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_HTTP_EXTERNAL_URI}
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://${ELASTICSEARCH_USERNAME}:${ELASTIC_PASSWORD}@elasticsearch:9200
      # - GRAYLOG_MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      # - GRAYLOG_MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog-net
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Веб-интерфейс Graylog и REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      - 1515:1515
      - 1516:1516
      - 1517:1517
      # Syslog UDP
      - 1514:1514/udp
      - 1515:1515/udp
      - 1516:1516/udp
      - 1517:1517/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

# Тома для сохранения данных, см. https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  mongo_data:
  elasticsearch-data:
  graylog_journal:

networks:
    graylog-net: